# Generated by Django 5.1.5 on 2025-01-30 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpaybenefit',
            options={'verbose_name': 'About pay benefit', 'verbose_name_plural': 'About pay benefits'},
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'About us', 'verbose_name_plural': 'About us'},
        ),
        migrations.AlterModelOptions(
            name='additionalbenefits',
            options={'verbose_name': 'Additional benefits', 'verbose_name_plural': 'Additional benefits'},
        ),
        migrations.AlterModelOptions(
            name='additionalbenefitsitem',
            options={'verbose_name': 'Additional benefits item', 'verbose_name_plural': 'Additional benefits items'},
        ),
        migrations.AlterModelOptions(
            name='apartadvantage',
            options={'verbose_name': 'Apart advantage', 'verbose_name_plural': 'Apart advantage'},
        ),
        migrations.AlterModelOptions(
            name='apartadvantagecategory',
            options={'verbose_name': 'Apart advantage category', 'verbose_name_plural': 'Apart advantage category'},
        ),
        migrations.AlterModelOptions(
            name='benefitbanner',
            options={'verbose_name': 'Benefit banner', 'verbose_name_plural': 'Benefit banners'},
        ),
        migrations.AlterModelOptions(
            name='benefitleasingbanner',
            options={'verbose_name': 'Benefit leasing banner', 'verbose_name_plural': 'Benefit leasing banners'},
        ),
        migrations.AlterModelOptions(
            name='benefitleasinginformation',
            options={'verbose_name': 'Benefit leasing information', 'verbose_name_plural': 'Benefit leasing informations'},
        ),
        migrations.AlterModelOptions(
            name='benefitleasinginformationitem',
            options={'verbose_name': 'Benefit leasing information item', 'verbose_name_plural': 'Benefit leasing information items'},
        ),
        migrations.AlterModelOptions(
            name='benefitleasingstar',
            options={'verbose_name': 'Benefit leasing star', 'verbose_name_plural': 'Benefit leasing stars'},
        ),
        migrations.AlterModelOptions(
            name='cdlholderadvantage',
            options={'verbose_name': 'CDL holder advantage', 'verbose_name_plural': 'CDL holder advantage'},
        ),
        migrations.AlterModelOptions(
            name='cdlholderbanner',
            options={'verbose_name': 'CDL holder banner', 'verbose_name_plural': 'CDL holder banners'},
        ),
        migrations.AlterModelOptions(
            name='companyculture',
            options={'verbose_name': 'Company culture', 'verbose_name_plural': 'Company culture'},
        ),
        migrations.AlterModelOptions(
            name='companyculturebanner',
            options={'ordering': ('-created_at',), 'verbose_name': 'Company culture banner', 'verbose_name_plural': 'Company culture banners'},
        ),
        migrations.AlterModelOptions(
            name='companycultureitem',
            options={'verbose_name': 'Company culture item', 'verbose_name_plural': 'Company culture items'},
        ),
        migrations.AlterModelOptions(
            name='companyprogramsbanner',
            options={'verbose_name': 'Company programs banner', 'verbose_name_plural': 'Company programs banners'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterModelOptions(
            name='darnews',
            options={'verbose_name': 'Dar news', 'verbose_name_plural': 'Dar news'},
        ),
        migrations.AlterModelOptions(
            name='darnewsbanner',
            options={'verbose_name': 'Dar news banner', 'verbose_name_plural': 'Dar news banners'},
        ),
        migrations.AlterModelOptions(
            name='driverawardbanner',
            options={'verbose_name': 'Driver award banner', 'verbose_name_plural': 'Driver award banners'},
        ),
        migrations.AlterModelOptions(
            name='drivertrainingprogrambanner',
            options={'verbose_name': 'Driver training program banner', 'verbose_name_plural': 'Driver training program banners'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipments'},
        ),
        migrations.AlterModelOptions(
            name='equipmentbanner',
            options={'verbose_name': 'Equipment banner', 'verbose_name_plural': 'Equipment banners'},
        ),
        migrations.AlterModelOptions(
            name='flatbeddivisionbanner',
            options={'verbose_name': 'Flatbed division banner', 'verbose_name_plural': 'Flatbed division banners'},
        ),
        migrations.AlterModelOptions(
            name='holidayobserver',
            options={'verbose_name': 'Holiday observer', 'verbose_name_plural': 'Holiday observers'},
        ),
        migrations.AlterModelOptions(
            name='holidayobserveritem',
            options={'verbose_name': 'Holiday observer item', 'verbose_name_plural': 'Holiday observer items'},
        ),
        migrations.AlterModelOptions(
            name='homebanner',
            options={'ordering': ('-created_at',), 'verbose_name': 'Home banner', 'verbose_name_plural': 'Home banners'},
        ),
        migrations.AlterModelOptions(
            name='homestatistic',
            options={'ordering': ('-created_at',), 'verbose_name': 'Home statistic', 'verbose_name_plural': 'Home statistics'},
        ),
        migrations.AlterModelOptions(
            name='jobssaidtransport',
            options={'verbose_name': 'Jobs said transport', 'verbose_name_plural': 'Jobs said transports'},
        ),
        migrations.AlterModelOptions(
            name='jobssaidtransportbanner',
            options={'verbose_name': 'Jobs said transport banner', 'verbose_name_plural': 'Jobs said transport banners'},
        ),
        migrations.AlterModelOptions(
            name='keyresponsibility',
            options={'verbose_name': 'Key responsibility', 'verbose_name_plural': 'Key responsibility'},
        ),
        migrations.AlterModelOptions(
            name='leadershipteambanner',
            options={'verbose_name': 'Leadership team banner', 'verbose_name_plural': 'Leadership team banners'},
        ),
        migrations.AlterModelOptions(
            name='leasepurchasebanner',
            options={'verbose_name': 'Lease purchase banner', 'verbose_name_plural': 'Lease purchase banners'},
        ),
        migrations.AlterModelOptions(
            name='leasepurchasecategory',
            options={'verbose_name': 'Lease purchase category', 'verbose_name_plural': 'Lease purchase categories'},
        ),
        migrations.AlterModelOptions(
            name='leasepurchasedefinition',
            options={'verbose_name': 'Lease purchase definition', 'verbose_name_plural': 'Lease purchase definitions'},
        ),
        migrations.AlterModelOptions(
            name='leasepurchaseitem',
            options={'verbose_name': 'Lease purchase item', 'verbose_name_plural': 'Lease purchase items'},
        ),
        migrations.AlterModelOptions(
            name='maintenancebanner',
            options={'verbose_name': 'Maintenance banner', 'verbose_name_plural': 'Maintenance banners'},
        ),
        migrations.AlterModelOptions(
            name='maintenancebenefit',
            options={'verbose_name': 'Maintenance benefit', 'verbose_name_plural': 'Maintenance benefits'},
        ),
        migrations.AlterModelOptions(
            name='maintenancebenefitimage',
            options={'verbose_name': 'Maintenance benefit', 'verbose_name_plural': 'Maintenance benefits'},
        ),
        migrations.AlterModelOptions(
            name='maintenancebenefittext',
            options={'verbose_name': 'Maintenance benefit', 'verbose_name_plural': 'Maintenance benefits'},
        ),
        migrations.AlterModelOptions(
            name='ourrequirement',
            options={'verbose_name': 'Our requirement', 'verbose_name_plural': 'Our requirements'},
        ),
        migrations.AlterModelOptions(
            name='paybenefitbanner',
            options={'verbose_name': 'Pay benefit banner', 'verbose_name_plural': 'Pay benefits banner'},
        ),
        migrations.AlterModelOptions(
            name='qualificationexpectation',
            options={'verbose_name': 'Qualification expectation', 'verbose_name_plural': 'Qualification expectations'},
        ),
        migrations.AlterModelOptions(
            name='qualificationexpectationbanner',
            options={'verbose_name': 'Qualification expectation banner', 'verbose_name_plural': 'Qualification expectation banners'},
        ),
        migrations.AlterModelOptions(
            name='refrigerateddivisionbanner',
            options={'verbose_name': 'Refrigerated division banner', 'verbose_name_plural': 'Refrigerated division banners'},
        ),
        migrations.AlterModelOptions(
            name='safetychampionawards',
            options={'verbose_name': 'Safety champion awards', 'verbose_name_plural': 'Safety champion awards'},
        ),
        migrations.AlterModelOptions(
            name='safetychampionawardsstar',
            options={'verbose_name': 'Safety champion awards star', 'verbose_name_plural': 'Safety champion awards stars'},
        ),
        migrations.AlterModelOptions(
            name='standardleasecategory',
            options={'verbose_name': 'Standard lease category', 'verbose_name_plural': 'Standard lease categories'},
        ),
        migrations.AlterModelOptions(
            name='standardleasedefinition',
            options={'verbose_name': 'Standard lease definition', 'verbose_name_plural': 'Standard lease definitions'},
        ),
        migrations.AlterModelOptions(
            name='standardleaseitem',
            options={'verbose_name': 'Standard lease item', 'verbose_name_plural': 'Standard lease items'},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Team member', 'verbose_name_plural': 'Team members'},
        ),
        migrations.AlterModelOptions(
            name='trainingprogram',
            options={'verbose_name': 'Training program', 'verbose_name_plural': 'Training program'},
        ),
        migrations.AlterModelOptions(
            name='trainingprogramcategory',
            options={'verbose_name': 'Training program category', 'verbose_name_plural': 'Training program categories'},
        ),
        migrations.AlterModelOptions(
            name='transportleadershipelite',
            options={'verbose_name': 'Transport leadership elite', 'verbose_name_plural': 'Transport leadership elites'},
        ),
        migrations.AlterModelOptions(
            name='transportleadershipelitestar',
            options={'verbose_name': 'Transport leadership elite star', 'verbose_name_plural': 'Transport leadership elite stars'},
        ),
    ]
