from django.urls import path
from api import views

urlpatterns = [
    path('home/', views.MainViewSet.as_view({'get': 'homepage'}), name='homepage'),
    path('company/culture/', views.MainViewSet.as_view({'get': 'company_culture'}), name='company_culture'),
    path('company/programs/', views.MainViewSet.as_view({'get': 'company_programs'}), name='company_programs'),
    path('leadership/team/', views.MainViewSet.as_view({'get': 'leadership_team'}), name='leadership_team'),
    path('leadership/team/members/', views.MainViewSet.as_view({'get': 'leadership_teams_members'})),
    path('leadership/team/members/<int:pk>/', views.MainViewSet.as_view({'get': 'leadership_teams_member'})),
    path('equipment/', views.MainViewSet.as_view({'get': 'equipment'}), name='equipment'),
    path('fleet/maintenance/', views.MainViewSet.as_view({'get': 'fleet_maintenance'}), name='fleet_maintenance'),
    path('dar/news/banner/', views.MainViewSet.as_view({'get': 'dar_news_banner'}), name='dar_news_banner'),
    path('dar/news/', views.MainViewSet.as_view({'get': 'dar_news_list'}), name='dar_news_list'),
    path('dar/news/<int:pk>/', views.MainViewSet.as_view({'get': 'dar_news_detail'}), name='dar_news_detail'),
    path('refrigerated/division/', views.MainViewSet.as_view({'get': 'refrigerated_division'})),
    path('flatbed/division/', views.MainViewSet.as_view({'get': 'flatbed_division'}), name='flatbed_division'),
    path('qualification/expectation/', views.MainViewSet.as_view({'get': 'qualification_expectation'})),
    path('pay/benefit/', views.MainViewSet.as_view({'get': 'pay_benefit_banner'})),
    path('driver/training/program/', views.MainViewSet.as_view({'get': 'driver_training_program_banner'})),
    path('cdl/holder/', views.MainViewSet.as_view({'get': 'cdl_holder_banner'})),
    path('driver/award/', views.MainViewSet.as_view({'get': 'driver_award_banner'})),
    path('jobs/said/transport/banner/', views.MainViewSet.as_view({'get': 'jobs_said_transport_banner'})),
    path('jobs/said/transport/', views.MainViewSet.as_view({'get': 'jobs_said_transport'})),
    path('jobs/said/transport/<int:pk>/', views.MainViewSet.as_view({'get': 'jobs_said_transport_detail'})),
    path('benefit/banner', views.MainViewSet.as_view({'get': 'benefit_banner'})),
    path('company/culture/two', views.MainViewSet.as_view({'get': 'company_culture_two'})),
    path('lease/purchase/banner', views.MainViewSet.as_view({'get': 'lease_purchase_banner'})),
    path('benefit/leasing/banner/', views.MainViewSet.as_view({'get': 'benefit_leasing_banner'})),
    path('about/us', views.MainViewSet.as_view({'get': 'about_us'})),
    path('contact/', views.MainViewSet.as_view({'post': 'contact'})),
]
